### ISSUE TITLE
Dotrun output fatal error ? 

### ISSUE THREAD

**Issue by hwpplayer1** [canonical-web-and-design/canonical.com#387]
```
[sudo] password for hwpplayer1: 
Traceback (most recent call last):
  File "/snap/dotrun/38/bin/dotrun", line 33, in <module>
    sys.exit(load_entry_point('canonicalwebteam.dotrun==0.0.0', 'console_scripts', 'dotrun')())
  File "/snap/dotrun/38/lib/python3.6/site-packages/canonicalwebteam/dotrun/__init__.py", line 135, in cli
    dotrun.install(force=False)
  File "/snap/dotrun/38/lib/python3.6/site-packages/canonicalwebteam/dotrun/models.py", line 95, in install
    self._install_yarn_dependencies(force=force)
  File "/snap/dotrun/38/lib/python3.6/site-packages/canonicalwebteam/dotrun/models.py", line 239, in _install_yarn_dependencies
    current_state = self._get_yarn_state()
  File "/snap/dotrun/38/lib/python3.6/site-packages/canonicalwebteam/dotrun/models.py", line 202, in _get_yarn_state
    os.path.join(self.path, "package.json"), "rb"
PermissionError: [Errno 13] Permission denied: '/media/hwpplayer1/d80f1c61-03b1-45df-a9e0-76fd979b604d/sourceforge/masscollabs/canonical/canonical.com/package.json'
hwpplayer1@hwpplayer1-Aspire-V3-772G:/media/hwpplayer1/d80f1c61-03b1-45df-a9e0-76fd979b604d/sourceforge/masscollabs/canonical/canonical.com$ sudo apt-get install yarnpkg
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
yarnpkg is already the newest version (1.22.10+~cs22.25.14-2).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```
```

hwpplayer1@hwpplayer1-Aspire-V3-772G:/media/hwpplayer1/d80f1c61-03b1-45df-a9e0-76fd979b604d/sourceforge/masscollabs/canonical/canonical.com$ sudo su
root@hwpplayer1-Aspire-V3-772G:/media/hwpplayer1/d80f1c61-03b1-45df-a9e0-76fd979b604d/sourceforge/masscollabs/canonical/canonical.com# dotrun
Traceback (most recent call last):
  File "/snap/dotrun/38/bin/dotrun", line 33, in <module>
    sys.exit(load_entry_point('canonicalwebteam.dotrun==0.0.0', 'console_scripts', 'dotrun')())
  File "/snap/dotrun/38/lib/python3.6/site-packages/canonicalwebteam/dotrun/__init__.py", line 135, in cli
    dotrun.install(force=False)
  File "/snap/dotrun/38/lib/python3.6/site-packages/canonicalwebteam/dotrun/models.py", line 95, in install
    self._install_yarn_dependencies(force=force)
  File "/snap/dotrun/38/lib/python3.6/site-packages/canonicalwebteam/dotrun/models.py", line 239, in _install_yarn_dependencies
    current_state = self._get_yarn_state()
  File "/snap/dotrun/38/lib/python3.6/site-packages/canonicalwebteam/dotrun/models.py", line 202, in _get_yarn_state
    os.path.join(self.path, "package.json"), "rb"
PermissionError: [Errno 13] Permission denied: '/media/hwpplayer1/d80f1c61-03b1-45df-a9e0-76fd979b604d/sourceforge/masscollabs/canonical/canonical.com/package.json'
root@hwpplayer1-Aspire-V3-772G:/media/hwpplayer1/d80f1c61-03b1-45df-a9e0-76fd979b604d/sourceforge/masscollabs/canonical/canonical.com# 
```

**Comment by hwpplayer1** [comment]
It works on /home/
